name: tests

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - develop
      - "release/*"
  pull_request:

jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 150
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        os: [ ubuntu-latest ]
        use-graph: [ 0, 1 ]
        python-version: [ 3.7, 3.8 ]
        include:
          - os: macos-latest
          - use-graph: [ 0, 1 ]
          - python-version: [ 3.8 ]
    name: tests for Python ${{ matrix.python-version }} compiled = ${{ matrix.use-graph }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with pytest
        run: |
          pip install .[dev]
          ZFIT_DO_JIT=${{ matrix.use-graph }}
          coverage run --source=. --omit=".tox/*,*/test*,*/minimizers/interface.py,*/core/testing.py" --branch -m pytest .
          coverage report

          bash utils/ci/install_test_examples.sh

          bash utils/ci/testbuild_docs.sh


  notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        use-graph: [ 0, 1 ]
        python-version: [ 3.7, 3.8 ]
    name: Run notebooks, Python ${{ matrix.python-version }}, compiled = ${{ matrix.use-graph }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone Tutorials
        run: |
          mkdir -p ~/test_zfit_tutorials && cd ~/test_zfit_tutorials
          git clone https://github.com/zfit/zfit-tutorials.git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbval
          pip install -r zfit-tutorials/requirements.txt


      - name: Run notebooks
        run: |
          ZFIT_DO_JIT=${{ matrix.use-graph }}
          pytest --nbval-lax zfit-tutorials --ignore=zfit-tutorials/experimental
