name: tests

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - develop
      - "release/*"
      - "hotfix/*"
  pull_request:

jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    env:
      ZFIT_DO_JIT: ${{ matrix.use-graph }}

    timeout-minutes: 180
    strategy:
      max-parallel: 12
      fail-fast: False
      matrix:
        use-graph: [ 0, 1 ]  # HACK: just do with graph, eager too slow?
        python-version: [ 3.7, 3.8, 3.9 ]
        os: [ ubuntu-latest ]
        include:
          - os: macos-latest
            python-version: 3.9
            use-graph: 0
          - os: macos-latest
            python-version: 3.9
            use-graph: 1
          - os: windows-latest
            python-version: 3.9
            use-graph: 0
          - os: windows-latest
            python-version: 3.9
            use-graph: 1

    name: tests on ${{ matrix.os }} with ${{ matrix.python-version }} compiled = ${{ matrix.use-graph }}
    #    env:
    #      ZFIT_DO_JIT: ${{ matrix.use-graph }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=in-tree-build --ignore-requires-python .[alldev,ci]  # ignore python version
          # because of https://github.com/chaychoong/coveragepy-lcov/pull/1
      - name: Test with pytest
        run: |
          coverage run --source=. --omit=".tox/*,*/test*,*/minimizers/interface.py,*/core/testing.py" --branch -m pytest . -n3
          mkdir coverage && coveragepy-lcov --output_file_path ./coverage/lcov.info
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.use-graph }}-${{ matrix.python-version }}-ubuntu
          parallel: true

      - name: Run examples
        run: |
          ZFIT_DO_JIT=${{ matrix.use-graph }}
          bash utils/ci/install_test_examples.sh
      - name: Build the docs, check for failure
        run: |
          ZFIT_DO_JIT=${{ matrix.use-graph }}
          bash utils/ci/testbuild_docs.sh

  notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        use-graph: [ 0, 1 ]
        python-version: [ 3.7, 3.8 ]
    name: Run notebooks, Python ${{ matrix.python-version }}, compiled = ${{ matrix.use-graph }}
    env:
      ZFIT_DO_JIT: ${{ matrix.use-graph }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone Tutorials
        run: |
          git clone https://github.com/zfit/zfit-tutorials.git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbval
          pip install -r zfit-tutorials/requirements.txt

      - name: Run notebooks
        run: |
          pytest --nbval-lax zfit-tutorials --ignore=zfit-tutorials/experimental --ignore=zfit-tutorials/_unused

  finish:
    needs: unittests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
